# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-RQU2pzoT5e0ky9Ja-bnwX6e5lDKJ6H0
"""

!pip install nltk
!pip install newspaper3k

import nltk
from newspaper import Article

url = 'https://www.washingtonpost.com/technology/2020/09/25/privacy-check-blacklight/'
article = Article(url)

#Doing some Natural Language Processing
article.download()
article.parse()
nltk.download('punkt')
article.nlp()

#Getting Author, publish date, author, article text and summary
article.authors

article.publish_date

article.top_image

print(article.text)

print(article.summary)

